#!/usr/bin/env bash
# run_local.sh — exercise the whole rust-symbol-audit pipeline locally, offline
# where possible, against the real Rust toolchain. Proves the acceptance checks
# without needing a live GitHub Action.
#
# Requirements: rustup/cargo, rustfilt (cargo install rustfilt), a symbol lister
# (GNU nm, or rustup's llvm-nm which this script auto-detects on Windows).
set -uo pipefail

PROJECT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS="$PROJECT/scripts"
FIX="$PROJECT/test/fixtures"
WORK="${WORK:-D:/tmp/rsa-local}"
rm -rf "$WORK"; mkdir -p "$WORK"

# --- tool detection ---------------------------------------------------------
if ! command -v nm >/dev/null 2>&1; then
  NM_BIN="$(find "$(rustc --print sysroot)" -name 'llvm-nm*' 2>/dev/null | head -1)"
  if [ -n "$NM_BIN" ]; then export NM="$NM_BIN"; fi
fi
echo "NM       = ${NM:-nm}"
echo "RUSTFILT = $(command -v rustfilt || echo MISSING)"
echo "WORK     = $WORK"
echo

PASS=0; FAIL=0
ok()   { echo "  ✅ $1"; PASS=$((PASS+1)); }
bad()  { echo "  ❌ $1"; FAIL=$((FAIL+1)); }
have() { grep -qiE "$2" "$1"; }

# ===========================================================================
echo "### TEST A — build_crate + diff_symbols + risk_check (fixtures, offline)"
# Old (no net) and new (TcpStream + Command) versions of the same crate.
export RSA_FIXTURES="$FIX"
OLD_RLIB="$("$SCRIPTS/build_crate.sh" 0.1.0 netcap "$WORK/a/old" 2>"$WORK/a_old.log")"
NEW_RLIB="$("$SCRIPTS/build_crate.sh" 0.2.0 netcap "$WORK/a/new" 2>"$WORK/a_new.log")"
echo "  old rlib: ${OLD_RLIB:-<none>}"
echo "  new rlib: ${NEW_RLIB:-<none>}"
[ -f "$OLD_RLIB" ] && ok "old fixture built" || bad "old fixture build (see $WORK/a_old.log)"
[ -f "$NEW_RLIB" ] && ok "new fixture built" || bad "new fixture build (see $WORK/a_new.log)"

"$SCRIPTS/diff_symbols.sh" "$OLD_RLIB" "$NEW_RLIB" "$WORK/a" >/dev/null 2>>"$WORK/a_diff.log"
ADDED="$WORK/a/added_syms.txt"
have "$ADDED" 'TcpStream' && ok "added symbols include TcpStream" || bad "TcpStream not in added symbols"
have "$ADDED" 'Command'   && ok "added symbols include Command"   || bad "Command not in added symbols"

RISK_JSON="$("$SCRIPTS/risk_check.sh" "$ADDED" "$WORK/a" 2>>"$WORK/a_risk.log"; )"
TIER="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["tier"])' "$WORK/a/risk.json")"
echo "  overall tier = $TIER"
[ "$TIER" = "critical" ] && ok "TcpStream-gaining bump tiered CRITICAL (acceptance #3)" \
                         || bad "expected critical, got '$TIER'"
echo "  --- risk.tsv (top) ---"; head -6 "$WORK/a/risk.tsv" | sed 's/^/    /'
echo

# ===========================================================================
echo "### TEST B — parse_lockdiff on a real git repo (bump + no-change)"
REPO="$WORK/repo"; mkdir -p "$REPO/.git"
( cd "$REPO"
  git init -q
  git config user.email t@t.io; git config user.name tester
  cat > Cargo.lock <<'LOCK'
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "demo"
version = "0.1.0"
dependencies = ["netcap"]

[[package]]
name = "netcap"
version = "0.1.0"
LOCK
  git add -A; git commit -qm v1
  BASE="$(git rev-parse HEAD)"
  sed -i 's/version = "0.1.0"$/version = "0.2.0"/2' Cargo.lock  # bump netcap block (2nd occurrence)
  # ensure netcap bumped specifically:
  python3 - <<'PY'
import re,io
s=open("Cargo.lock").read()
s=s.replace('name = "netcap"\nversion = "0.1.0"','name = "netcap"\nversion = "0.2.0"')
open("Cargo.lock","w").write(s)
PY
  git add -A; git commit -qm v2
  echo "$BASE" > "$WORK/base_sha.txt"
)
BASE_SHA="$(cat "$WORK/base_sha.txt")"
( cd "$REPO"
  GITHUB_OUTPUT="$WORK/b_out.txt" "$SCRIPTS/parse_lockdiff.sh" "$BASE_SHA" HEAD "$WORK/b_lockdiff.tsv" >"$WORK/b_stdout.txt" 2>"$WORK/b.log"
)
echo "  lockdiff.tsv:"; sed 's/^/    /' "$WORK/b_lockdiff.tsv"
# grep -P (PCRE \t) is unavailable on this Git Bash locale; match a literal tab
# with grep -F instead.
grep -qF "$(printf 'netcap\t0.1.0\t0.2.0')" "$WORK/b_lockdiff.tsv" && ok "bump row emitted: netcap 0.1.0 -> 0.2.0" \
  || bad "expected netcap bump row"
have "$WORK/b_out.txt" 'changed=true' && ok "output changed=true" || bad "changed output wrong"

# no-change case: diff a commit against itself
( cd "$REPO"
  GITHUB_OUTPUT="$WORK/b_out2.txt" "$SCRIPTS/parse_lockdiff.sh" HEAD HEAD "$WORK/b_lockdiff2.tsv" >/dev/null 2>>"$WORK/b.log"
)
have "$WORK/b_out2.txt" 'changed=false' && ok "no-change -> changed=false (acceptance #4)" \
  || bad "no-change did not report changed=false"
[ ! -s "$WORK/b_lockdiff2.tsv" ] && ok "no-change TSV empty" || bad "no-change TSV should be empty"
echo

# ===========================================================================
echo "### TEST C — FULL pipeline: parse -> run_audit -> comment (dry-run, fixtures)"
export RSA_DRY_RUN=1 RSA_FIXTURES="$FIX"
CWORK="$WORK/c"; mkdir -p "$CWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$CWORK" MAX_CRATES=5 PR_NUMBER="" \
  bash -c "cd '$REPO' && GITHUB_OUTPUT='$CWORK/parse_out.txt' '$SCRIPTS/parse_lockdiff.sh' '$BASE_SHA' HEAD '$CWORK/lockdiff.tsv'" >/dev/null 2>"$CWORK/parse.log"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$CWORK" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  "$SCRIPTS/run_audit.sh" >"$CWORK/audit_stdout.txt" 2>"$CWORK/audit.log"
BODY="$CWORK/comment_body.md"
if [ -f "$BODY" ]; then
  ok "comment body produced"
  have "$BODY" 'CRITICAL'   && ok "comment flags CRITICAL"        || bad "comment missing CRITICAL"
  have "$BODY" 'TcpStream'  && ok "comment lists TcpStream symbol" || bad "comment missing TcpStream"
  have "$BODY" 'netcap'     && ok "comment names the crate"       || bad "comment missing crate name"
  have "$BODY" '\| risk \|' && ok "comment contains a symbol table (acceptance #2)" || bad "no table in comment"
else
  bad "no comment body (see $CWORK/audit.log)"
fi
echo "  --- comment_body.md ---"; sed 's/^/    /' "$BODY" 2>/dev/null | head -40
echo

# ===========================================================================
echo "### TEST D — real crates.io bump through build_crate (timing, acceptance #5)"
unset RSA_FIXTURES   # force real crates.io path
RC="once_cell"; RV_OLD="1.19.0"; RV_NEW="1.20.2"
DWORK="$WORK/d"; mkdir -p "$DWORK"
T0=$(date +%s)
D_OLD="$("$SCRIPTS/build_crate.sh" "$RV_OLD" "$RC" "$DWORK/old" 2>"$DWORK/old.log")"
D_NEW="$("$SCRIPTS/build_crate.sh" "$RV_NEW" "$RC" "$DWORK/new" 2>"$DWORK/new.log")"
T1=$(date +%s)
ELAPSED=$((T1-T0))
echo "  $RC $RV_OLD -> $RV_NEW built in ${ELAPSED}s"
echo "  old rlib: ${D_OLD:-<none>}"; echo "  new rlib: ${D_NEW:-<none>}"
[ -f "$D_OLD" ] && [ -f "$D_NEW" ] && ok "real crates.io versions built (build_crate crates.io path works)" \
  || bad "crates.io build failed (see $DWORK/*.log)"
if [ -f "$D_NEW" ]; then
  "$SCRIPTS/diff_symbols.sh" "$D_OLD" "$D_NEW" "$DWORK" >/dev/null 2>>"$DWORK/diff.log"
  N_ADDED="$(awk 'END{print NR+0}' "$DWORK/added_syms.txt" 2>/dev/null || echo 0)"
  echo "  added symbols in $RC bump: $N_ADDED"
  "$SCRIPTS/risk_check.sh" "$DWORK/added_syms.txt" "$DWORK" >/dev/null 2>>"$DWORK/risk.log"
  ok "diff+risk ran on real crate (added=$N_ADDED)"
fi
[ "$ELAPSED" -lt 240 ] && ok "single-crate bump under 4 min (${ELAPSED}s)" || bad "took ${ELAPSED}s (>240s)"
echo

# ===========================================================================
echo "==================================================================="
echo "RESULT: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] && echo "ALL GREEN" || echo "SOME FAILURES — inspect logs under $WORK"
exit "$FAIL"
