#!/usr/bin/env bash
# run_local.sh — exercise the whole rust-symbol-audit pipeline locally, offline
# where possible, against the real Rust toolchain. Proves the acceptance checks
# without needing a live GitHub Action.
#
# Requirements: rustup/cargo, rustfilt (cargo install rustfilt), a symbol lister
# (GNU nm, or rustup's llvm-nm which this script auto-detects on Windows).
set -uo pipefail

PROJECT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS="$PROJECT/scripts"
FIX="$PROJECT/test/fixtures"
# Portable scratch dir: RUNNER_TEMP on CI, else /tmp (works in Git Bash too).
WORK="${WORK:-${RUNNER_TEMP:-/tmp}/rsa-local}"
rm -rf "$WORK"; mkdir -p "$WORK"

# --- tool detection ---------------------------------------------------------
if ! command -v nm >/dev/null 2>&1; then
  NM_BIN="$(find "$(rustc --print sysroot)" -name 'llvm-nm*' 2>/dev/null | head -1)"
  if [ -n "$NM_BIN" ]; then export NM="$NM_BIN"; fi
fi
echo "NM       = ${NM:-nm}"
echo "RUSTFILT = $(command -v rustfilt || echo MISSING)"
echo "WORK     = $WORK"
echo

PASS=0; FAIL=0
ok()   { echo "  ✅ $1"; PASS=$((PASS+1)); }
bad()  { echo "  ❌ $1"; FAIL=$((FAIL+1)); }
have() { grep -qiE "$2" "$1"; }

# ===========================================================================
echo "### TEST A — build_crate + diff_symbols + risk_check (fixtures, offline)"
# Old (no net) and new (TcpStream + Command) versions of the same crate.
export RSA_FIXTURES="$FIX"
OLD_RLIB="$("$SCRIPTS/build_crate.sh" 0.1.0 netcap "$WORK/a/old" 2>"$WORK/a_old.log")"
NEW_RLIB="$("$SCRIPTS/build_crate.sh" 0.2.0 netcap "$WORK/a/new" 2>"$WORK/a_new.log")"
echo "  old rlib: ${OLD_RLIB:-<none>}"
echo "  new rlib: ${NEW_RLIB:-<none>}"
[ -f "$OLD_RLIB" ] && ok "old fixture built" || bad "old fixture build (see $WORK/a_old.log)"
[ -f "$NEW_RLIB" ] && ok "new fixture built" || bad "new fixture build (see $WORK/a_new.log)"
# Both probes share one target dir, so both versions' rlibs land in the same
# deps/ and the filename stops identifying a version. Picking the wrong one
# would not fail anything here -- it would quietly audit a version twice.
[ "$OLD_RLIB" != "$NEW_RLIB" ] && ok "shared target dir still resolves the two versions apart" \
                               || bad "both versions resolved to one rlib: $NEW_RLIB"
[ "$(dirname "$OLD_RLIB")" = "$(dirname "$NEW_RLIB")" ] && ok "both probes did share one target dir" \
                                                        || bad "probes did not share a target dir"

"$SCRIPTS/diff_symbols.sh" "$OLD_RLIB" "$NEW_RLIB" "$WORK/a" >/dev/null 2>>"$WORK/a_diff.log"
ADDED="$WORK/a/added_syms.txt"
have "$ADDED" 'TcpStream' && ok "added symbols include TcpStream" || bad "TcpStream not in added symbols"
have "$ADDED" 'Command'   && ok "added symbols include Command"   || bad "Command not in added symbols"

RISK_JSON="$("$SCRIPTS/risk_check.sh" "$ADDED" "$WORK/a" 2>>"$WORK/a_risk.log"; )"
TIER="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["tier"])' "$WORK/a/risk.json")"
echo "  overall tier = $TIER"
[ "$TIER" = "critical" ] && ok "TcpStream-gaining bump tiered CRITICAL (acceptance #3)" \
                         || bad "expected critical, got '$TIER'"
echo "  --- risk.tsv (top) ---"; head -6 "$WORK/a/risk.tsv" | sed 's/^/    /'
echo

# ===========================================================================
echo "### TEST B — parse_lockdiff on a real git repo (bump + no-change)"
REPO="$WORK/repo"; mkdir -p "$REPO/.git"
( cd "$REPO"
  git init -q
  git config user.email t@t.io; git config user.name tester
  cat > Cargo.lock <<'LOCK'
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "demo"
version = "0.1.0"
dependencies = ["netcap"]

[[package]]
name = "netcap"
version = "0.1.0"
LOCK
  git add -A; git commit -qm v1
  BASE="$(git rev-parse HEAD)"
  sed -i 's/version = "0.1.0"$/version = "0.2.0"/2' Cargo.lock  # bump netcap block (2nd occurrence)
  # ensure netcap bumped specifically:
  python3 - <<'PY'
import re,io
s=open("Cargo.lock").read()
s=s.replace('name = "netcap"\nversion = "0.1.0"','name = "netcap"\nversion = "0.2.0"')
open("Cargo.lock","w").write(s)
PY
  git add -A; git commit -qm v2
  echo "$BASE" > "$WORK/base_sha.txt"
)
BASE_SHA="$(cat "$WORK/base_sha.txt")"
( cd "$REPO"
  GITHUB_OUTPUT="$WORK/b_out.txt" "$SCRIPTS/parse_lockdiff.sh" "$BASE_SHA" HEAD "$WORK/b_lockdiff.tsv" >"$WORK/b_stdout.txt" 2>"$WORK/b.log"
)
echo "  lockdiff.tsv:"; sed 's/^/    /' "$WORK/b_lockdiff.tsv"
# grep -P (PCRE \t) is unavailable on this Git Bash locale; match a literal tab
# with grep -F instead.
grep -qF "$(printf 'netcap\t0.1.0\t0.2.0')" "$WORK/b_lockdiff.tsv" && ok "bump row emitted: netcap 0.1.0 -> 0.2.0" \
  || bad "expected netcap bump row"
have "$WORK/b_out.txt" 'changed=true' && ok "output changed=true" || bad "changed output wrong"

# no-change case: diff a commit against itself
( cd "$REPO"
  GITHUB_OUTPUT="$WORK/b_out2.txt" "$SCRIPTS/parse_lockdiff.sh" HEAD HEAD "$WORK/b_lockdiff2.tsv" >/dev/null 2>>"$WORK/b.log"
)
have "$WORK/b_out2.txt" 'changed=false' && ok "no-change -> changed=false (acceptance #4)" \
  || bad "no-change did not report changed=false"
[ ! -s "$WORK/b_lockdiff2.tsv" ] && ok "no-change TSV empty" || bad "no-change TSV should be empty"
echo

# ===========================================================================
echo "### TEST C — FULL pipeline: parse -> run_audit -> comment (dry-run, fixtures)"
export RSA_DRY_RUN=1 RSA_FIXTURES="$FIX"
CWORK="$WORK/c"; mkdir -p "$CWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$CWORK" MAX_CRATES=5 PR_NUMBER="" \
  bash -c "cd '$REPO' && GITHUB_OUTPUT='$CWORK/parse_out.txt' '$SCRIPTS/parse_lockdiff.sh' '$BASE_SHA' HEAD '$CWORK/lockdiff.tsv'" >/dev/null 2>"$CWORK/parse.log"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$CWORK" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  "$SCRIPTS/run_audit.sh" >"$CWORK/audit_stdout.txt" 2>"$CWORK/audit.log"
BODY="$CWORK/comment_body.md"
if [ -f "$BODY" ]; then
  ok "comment body produced"
  have "$BODY" 'CRITICAL'   && ok "comment flags CRITICAL"        || bad "comment missing CRITICAL"
  have "$BODY" 'TcpStream'  && ok "comment lists TcpStream symbol" || bad "comment missing TcpStream"
  have "$BODY" 'netcap'     && ok "comment names the crate"       || bad "comment missing crate name"
  have "$BODY" '\| risk \|' && ok "comment contains a symbol table (acceptance #2)" || bad "no table in comment"
else
  bad "no comment body (see $CWORK/audit.log)"
fi
echo "  --- comment_body.md ---"; sed 's/^/    /' "$BODY" 2>/dev/null | head -40
echo

# ===========================================================================
echo "### TEST D — real crates.io bump through build_crate (timing, acceptance #5)"
unset RSA_FIXTURES   # force real crates.io path
RC="once_cell"; RV_OLD="1.19.0"; RV_NEW="1.20.2"
DWORK="$WORK/d"; mkdir -p "$DWORK"
T0=$(date +%s)
D_OLD="$("$SCRIPTS/build_crate.sh" "$RV_OLD" "$RC" "$DWORK/old" 2>"$DWORK/old.log")"
D_NEW="$("$SCRIPTS/build_crate.sh" "$RV_NEW" "$RC" "$DWORK/new" 2>"$DWORK/new.log")"
T1=$(date +%s)
ELAPSED=$((T1-T0))
echo "  $RC $RV_OLD -> $RV_NEW built in ${ELAPSED}s"
echo "  old rlib: ${D_OLD:-<none>}"; echo "  new rlib: ${D_NEW:-<none>}"
[ -f "$D_OLD" ] && [ -f "$D_NEW" ] && ok "real crates.io versions built (build_crate crates.io path works)" \
  || bad "crates.io build failed (see $DWORK/*.log)"
if [ -f "$D_NEW" ]; then
  "$SCRIPTS/diff_symbols.sh" "$D_OLD" "$D_NEW" "$DWORK" >/dev/null 2>>"$DWORK/diff.log"
  N_ADDED="$(awk 'END{print NR+0}' "$DWORK/added_syms.txt" 2>/dev/null || echo 0)"
  echo "  added symbols in $RC bump: $N_ADDED"
  "$SCRIPTS/risk_check.sh" "$DWORK/added_syms.txt" "$DWORK" >/dev/null 2>>"$DWORK/risk.log"
  ok "diff+risk ran on real crate (added=$N_ADDED)"
fi
[ "$ELAPSED" -lt 240 ] && ok "single-crate bump under 4 min (${ELAPSED}s)" || bad "took ${ELAPSED}s (>240s)"
echo

# ===========================================================================
echo "### TEST E — source lane: build.rs newly added (netcap 0.2.0 -> 0.3.0)"
export RSA_FIXTURES="$FIX"          # re-export (TEST D unset it)
EWORK="$WORK/e"; mkdir -p "$EWORK"
"$SCRIPTS/inspect_source.sh" netcap 0.2.0 0.3.0 "$EWORK" >/dev/null 2>"$EWORK/e.log"
echo "  --- source_findings.tsv ---"; sed 's/^/    /' "$EWORK/source_findings.tsv" 2>/dev/null
have "$EWORK/source_findings.tsv" 'build-script' && ok "build.rs addition detected (symbol lane is blind to this)" \
  || bad "build.rs not detected"
ETIER="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["tier"])' "$EWORK/source.json" 2>/dev/null || echo none)"
[ "$ETIER" = "critical" ] && ok "malicious build.rs (shells out) tiered CRITICAL" || bad "expected critical, got '$ETIER'"
echo

# ===========================================================================
echo "### TEST F — source lane: crate becomes a proc-macro (procm 0.1.0 -> 0.2.0)"
FWORK="$WORK/f"; mkdir -p "$FWORK"
"$SCRIPTS/inspect_source.sh" procm 0.1.0 0.2.0 "$FWORK" >/dev/null 2>"$FWORK/f.log"
echo "  --- source_findings.tsv ---"; sed 's/^/    /' "$FWORK/source_findings.tsv" 2>/dev/null
have "$FWORK/source_findings.tsv" 'proc-macro' && ok "proc-macro transition detected" || bad "proc-macro not detected"
FTIER="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["tier"])' "$FWORK/source.json" 2>/dev/null || echo none)"
[ "$FTIER" = "high" ] && ok "proc-macro transition tiered HIGH" || bad "expected high, got '$FTIER'"
echo

# ===========================================================================
echo "### TEST G — config: ignore_crates + [allow] suppression"
GWORK="$WORK/g"; mkdir -p "$GWORK"
cat > "$GWORK/cfg.toml" <<'TOML'
ignore_crates = ["libc", "netcap"]

[allow]
netcap = ["TcpStream", "Command"]
TOML
python3 "$SCRIPTS/read_config.py" "$GWORK/cfg.toml" > "$GWORK/norm.txt" 2>"$GWORK/g.log"
echo "  --- normalized config ---"; sed 's/^/    /' "$GWORK/norm.txt"
have "$GWORK/norm.txt" 'IGNORE.*netcap'          && ok "read_config emits IGNORE netcap" || bad "IGNORE missing"
have "$GWORK/norm.txt" 'ALLOW.*netcap.*TcpStream' && ok "read_config emits ALLOW netcap TcpStream" || bad "ALLOW missing"

# full pipeline with netcap ignored -> overall tier none
printf 'ignore_crates = ["netcap"]\n' > "$GWORK/ignore.toml"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$GWORK/run" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  RSA_CONFIG="$GWORK/ignore.toml" GITHUB_OUTPUT="$GWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$GWORK/audit.log"
have "$GWORK/out.txt" 'tier=none'                  && ok "ignored crate -> overall tier none" || bad "expected tier=none ($(grep '^tier=' "$GWORK/out.txt" 2>/dev/null))"
have "$GWORK/run/comment_body.md" 'ignored'        && ok "comment notes the crate was ignored" || bad "comment missing 'ignored'"

# full pipeline with the critical symbols allow-listed -> tier drops from critical
cat > "$GWORK/allow.toml" <<'TOML'
[allow]
netcap = ["TcpStream", "Command", "process", "socket"]
TOML
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$GWORK/run2" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  RSA_CONFIG="$GWORK/allow.toml" GITHUB_OUTPUT="$GWORK/out2.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$GWORK/audit2.log"
echo "  out2: $(tr '\n' ' ' < "$GWORK/out2.txt")"
have "$GWORK/out2.txt" 'tier=none' && ok "allow patterns suppressed the critical symbols" \
  || bad "allow did not lower tier ($(grep '^tier=' "$GWORK/out2.txt" 2>/dev/null))"
echo

# ===========================================================================
echo "### TEST H — dependency-tree diff detects a newly-pulled crate"
HWORK="$WORK/h"; mkdir -p "$HWORK"
cat > "$HWORK/old.lock" <<'LOCK'
[[package]]
name = "probe_lib"
version = "0.1.0"

[[package]]
name = "widget"
version = "1.0.0"
LOCK
cat > "$HWORK/new.lock" <<'LOCK'
[[package]]
name = "probe_lib"
version = "0.1.0"

[[package]]
name = "widget"
version = "1.1.0"

[[package]]
name = "reqwest"
version = "0.12.0"
LOCK
NEWPKGS="$( . "$SCRIPTS/lib.sh"; comm -13 \
  <(pkg_set "$HWORK/old.lock" | awk '{print $1}' | sort -u) \
  <(pkg_set "$HWORK/new.lock" | awk '{print $1}' | sort -u) )"
echo "  new packages in tree: $(echo $NEWPKGS)"
printf '%s\n' "$NEWPKGS" | grep -qx reqwest && ok "newly-pulled dependency 'reqwest' detected" || bad "reqwest not detected"
echo

# ===========================================================================
echo "### TEST I — fail-on gating"
IWORK="$WORK/i"; mkdir -p "$IWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$IWORK/c" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  FAIL_ON=critical GITHUB_OUTPUT="$IWORK/outc.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$IWORK/c.log"
IRC=$?
echo "  run_audit exit with FAIL_ON=critical on a critical bump: $IRC"
[ "$IRC" -ne 0 ] && ok "fail-on=critical fails the check on a critical bump" || bad "expected non-zero exit, got $IRC"
[ -f "$IWORK/c/comment_body.md" ] && ok "comment still produced before failing" || bad "no comment body on gated run"

LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$IWORK/n" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  FAIL_ON=none GITHUB_OUTPUT="$IWORK/outn.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$IWORK/n.log"
INRC=$?
[ "$INRC" -eq 0 ] && ok "fail-on=none stays advisory (exit 0)" || bad "fail-on=none should exit 0, got $INRC"
echo

# ===========================================================================
echo "### TEST J — sticky comment marker present"
have "$CWORK/comment_body.md" 'rust-symbol-audit -->' && ok "comment body carries the sticky-comment marker" \
  || bad "sticky marker missing from comment body"
echo

# ===========================================================================
echo "### TEST K — review ledger ratchet: a signed-off version -> tier none"
export RSA_FIXTURES="$FIX"
KWORK="$WORK/k"; mkdir -p "$KWORK"
printf '[[review]]\ncrate = "netcap"\nversion = "0.2.0"\nreviewed_by = "carol"\n' > "$KWORK/reviews.toml"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$KWORK/run" REVIEWS="$KWORK/reviews.toml" RSA_DRY_RUN=1 PR_NUMBER="" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 GITHUB_OUTPUT="$KWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$KWORK/run.log"
have "$KWORK/out.txt" 'tier=none' && ok "signed-off netcap 0.2.0 -> overall tier none (the ratchet)" \
  || bad "expected tier=none ($(grep '^tier=' "$KWORK/out.txt" 2>/dev/null))"
have "$KWORK/run/comment_body.md" 'reviewed ✅|Signed off in the review ledger' && ok "comment shows the reviewed badge" || bad "no reviewed badge"
echo

# ===========================================================================
echo "### TEST L — advisories/provenance are NOT hidden by a stale sign-off"
LWORK="$WORK/l"; mkdir -p "$LWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$LWORK/run" REVIEWS="$KWORK/reviews.toml" \
  RSA_CRATESIO_FIXTURE="$FIX/cratesio" RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$LWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$LWORK/run.log"
have "$LWORK/out.txt" 'tier=high' && ok "provenance change survives the sign-off (tier high, not none)" \
  || bad "expected tier=high ($(grep '^tier=' "$LWORK/out.txt" 2>/dev/null))"
have "$LWORK/run/comment_body.md" 'DIFFERENT account' && ok "publisher-change surfaced despite the sign-off" || bad "publisher-change was hidden"
echo

# ===========================================================================
echo "### TEST M — provenance.sh detects a publisher change (mock crates.io)"
MWORK="$WORK/m"; mkdir -p "$MWORK"
RSA_CRATESIO_FIXTURE="$FIX/cratesio" "$SCRIPTS/provenance.sh" netcap 0.1.0 0.2.0 "$MWORK" >/dev/null 2>"$MWORK/m.log"
echo "  --- provenance_findings.tsv ---"; sed 's/^/    /' "$MWORK/provenance_findings.tsv" 2>/dev/null
have "$MWORK/provenance_findings.tsv" 'publisher-change' && ok "publisher-change detected (original-author -> attacker-acct)" || bad "publisher-change not detected"
echo

# ===========================================================================
echo "### TEST N — advisories.sh detects a RustSec/OSV advisory (mock)"
N2WORK="$WORK/n2"; mkdir -p "$N2WORK"
RSA_ADVISORY_FIXTURE="$FIX/osv" "$SCRIPTS/advisories.sh" vulncrate 1.0.0 "$N2WORK" >/dev/null 2>"$N2WORK/n.log"
NRC=$?
echo "  --- advisory_findings.tsv ---"; sed 's/^/    /' "$N2WORK/advisory_findings.tsv" 2>/dev/null
have "$N2WORK/advisory_findings.tsv" 'RUSTSEC-2099-0001' && ok "advisory RUSTSEC-2099-0001 detected via OSV mock" || bad "advisory not detected"
# The TSV is written by an earlier python block than the JSON, so asserting only
# on the TSV cannot see the lane dying halfway. It did: on Windows the second
# block hit cp1252 and advisories.json was never written, for three releases,
# with this test green. Assert the exit code and the JSON too.
[ "$NRC" -eq 0 ] && ok "advisories.sh exits 0 on a hit (not a half-run lane)" || bad "advisories.sh exited $NRC"
python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert d['tier']=='high' and d['findings'][0]['kind']=='advisory'" "$N2WORK/advisories.json" 2>/dev/null \
  && ok "advisories.json written and well-formed (the half-run this test used to miss)" || bad "advisories.json missing/malformed"
grep -q '�' "$N2WORK/advisory_findings.tsv" 2>/dev/null \
  && bad "advisory detail carries a replacement char (cp1252 mangling is back)" \
  || ok "advisory detail survives non-ASCII intact (PYTHONUTF8)"
echo

# ===========================================================================
echo "### TEST O — Dependabot auto-merge recommendation"
OWORK="$WORK/o"; mkdir -p "$OWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$OWORK/r" REVIEWS="/nonexistent" PR_AUTHOR="dependabot[bot]" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$OWORK/r_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$OWORK/r.log"
have "$OWORK/r_out.txt" 'recommendation=review' && ok "risky bot bump -> recommendation=review" || bad "expected recommendation=review"
have "$OWORK/r/comment_body.md" 'Bot dependency bump' && ok "bot banner present in comment" || bad "bot banner missing"
# Prepending the banner used to go through "$(cat)", which strips the sections
# file's trailing newlines -- the closing legend's `---` then landed glued to the
# last block ("</details>---") and stopped rendering as a rule.
grep -qE '^(</details>|.+)---$' "$OWORK/r/comment_body.md" \
  && bad "banner path glued a block to the trailing '---' rule" \
  || ok "bot banner keeps the sections' trailing newlines (no glued '---')"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$OWORK/a" REVIEWS="$KWORK/reviews.toml" PR_AUTHOR="dependabot[bot]" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$OWORK/a_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$OWORK/a.log"
have "$OWORK/a_out.txt" 'recommendation=auto-merge' && ok "clean (signed-off) bot bump -> recommendation=auto-merge" || bad "expected recommendation=auto-merge"
echo

# ===========================================================================
echo "### TEST P — machine-readable evidence report (audit-report.json)"
have "$OWORK/r/audit-report.json" 'rust-symbol-audit' && ok "evidence report produced" || bad "no evidence report"
python3 -c "import json; d=json.load(open('$OWORK/r/audit-report.json')); assert d['schema']==1 and d['overall_tier']=='critical' and d['crates'] and d['crates'][0]['symbols']" 2>/dev/null \
  && ok "evidence JSON well-formed (critical verdict + per-crate symbols)" || bad "evidence JSON malformed/unexpected"
echo

# ===========================================================================
echo "### TEST Q — build.rs concrete diff shown in the comment (netcap 0.2.0 -> 0.3.0)"
QWORK="$WORK/q"; mkdir -p "$QWORK"
printf 'netcap\t0.2.0\t0.3.0\n' > "$QWORK/lockdiff.tsv"
LOCKDIFF_TSV="$QWORK/lockdiff.tsv" WORK="$QWORK/run" REVIEWS="/nonexistent" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$QWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$QWORK/run.log"
have "$QWORK/run/comment_body.md" 'show build script' && ok "comment includes the build.rs <details> block" || bad "no build.rs details block"
have "$QWORK/run/comment_body.md" 'build-time code executed' && ok "comment shows the ACTUAL build.rs code, not just 'it changed'" || bad "build.rs content not shown"
echo

# ===========================================================================
echo "### TEST R — read_reviews.py: ALL vs ACCEPT normalization"
R2WORK="$WORK/r2"; mkdir -p "$R2WORK"
cat > "$R2WORK/reviews.toml" <<'TOML'
[[review]]
crate = "foo"
version = "1.0.0"
reviewed_by = "dave"

[[review]]
crate = "bar"
version = "2.0.0"
accept = ["TcpStream", "hyper"]
TOML
python3 "$SCRIPTS/read_reviews.py" "$R2WORK/reviews.toml" > "$R2WORK/norm.txt"
echo "  --- normalized ledger ---"; sed 's/^/    /' "$R2WORK/norm.txt"
have "$R2WORK/norm.txt" 'REVIEW.*foo.*1.0.0.*ALL.*dave'    && ok "whole-version sign-off -> ALL" || bad "ALL entry missing"
have "$R2WORK/norm.txt" 'REVIEW.*bar.*2.0.0.*ACCEPT.*hyper' && ok "per-capability accept -> ACCEPT" || bad "ACCEPT entry missing"
echo

# ===========================================================================
echo "### TEST S — newly-added crate (empty old version) parses correctly + advisory fires"
# Regression for the IFS=tab field-collapse bug: a lockdiff row 'name<TAB><TAB>ver'
# must audit as old=<none> new=ver (not old=ver new=<empty>), so the build and
# advisory lanes actually run for newly-added crates.
export RSA_FIXTURES="$FIX"
SSWORK="$WORK/s"; mkdir -p "$SSWORK"
printf 'netcap\t\t0.2.0\n' > "$SSWORK/lockdiff.tsv"
LOCKDIFF_TSV="$SSWORK/lockdiff.tsv" WORK="$SSWORK/run" REVIEWS="/nonexistent" \
  RSA_CHECK_PROVENANCE=0 RSA_ADVISORY_FIXTURE="$FIX/osv" RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$SSWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$SSWORK/run.log"
have "$SSWORK/run.log" 'auditing netcap : <new> -> 0.2.0' \
  && ok "newly-added crate audited as old=<none> new=0.2.0 (empty-field bug fixed)" \
  || bad "newly-added crate misparsed: $(grep -o 'auditing netcap : .*' "$SSWORK/run.log" | head -1)"
have "$SSWORK/run/comment_body.md" 'RUSTSEC-2099-9999' \
  && ok "advisory lane fired for the newly-added crate (new version reached it)" \
  || bad "advisory not shown for newly-added crate"
echo

# ===========================================================================
echo "### TEST T — capability patterns: clipboard / input-device / screen-capture (issue #1)"
TTWORK="$WORK/t"; mkdir -p "$TTWORK"
cat > "$TTWORK/syms.txt" <<'SYMS'
arboard::Clipboard::set_text
<enigo::Enigo>::key_click
scrap::Capturer::frame
<nokhwa::Camera>::frame
cpal::traits::DeviceTrait::default_input_config
SYMS
"$SCRIPTS/risk_check.sh" "$TTWORK/syms.txt" "$TTWORK" >/dev/null 2>"$TTWORK/t.log"
echo "  --- risk.tsv ---"; sed 's/^/    /' "$TTWORK/risk.tsv" 2>/dev/null
TTIER="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["tier"])' "$TTWORK/risk.json" 2>/dev/null || echo none)"
[ "$TTIER" = "high" ] && ok "clipboard/input/capture symbols tier HIGH" || bad "expected high, got '$TTIER'"
have "$TTWORK/risk.tsv" 'arboard'  && ok "clipboard (arboard) flagged"    || bad "arboard not flagged"
have "$TTWORK/risk.tsv" 'enigo'    && ok "input device (enigo) flagged"   || bad "enigo not flagged"
have "$TTWORK/risk.tsv" 'Capturer' && ok "screen capture (scrap) flagged" || bad "scrap/Capturer not flagged"
echo

# ===========================================================================
echo "### TEST U — comment=false: summary-only mode (issue #2)"
export RSA_FIXTURES="$FIX"
UWORK="$WORK/u"; mkdir -p "$UWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$UWORK/run" REVIEWS="/nonexistent" PR_NUMBER="999" RSA_COMMENT=false \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 GITHUB_STEP_SUMMARY="$UWORK/summary.md" GITHUB_OUTPUT="$UWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$UWORK/run.log"
URC=$?
[ "$URC" -eq 0 ] && ok "run completes cleanly with comment=false (no post attempt)" || bad "run_audit exit $URC with comment=false"
have "$UWORK/summary.md" 'rust-symbol-audit'                 && ok "job summary still written in summary-only mode" || bad "job summary not written"
have "$UWORK/run.log" 'not posting a PR comment .comment=false' && ok "logged the comment=false skip"               || bad "no comment=false skip log"
have "$UWORK/out.txt" 'tier=critical'                        && ok "outputs still set in summary-only mode"         || bad "tier output missing"
echo

# ===========================================================================
echo "### TEST V — crate names link to crates.io (issue #3)"
export RSA_FIXTURES="$FIX"
VWORK="$WORK/v"; mkdir -p "$VWORK"
# flagged crate -> linked section header
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$VWORK/f" REVIEWS="/nonexistent" RSA_DRY_RUN=1 PR_NUMBER="" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 GITHUB_OUTPUT="$VWORK/f_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$VWORK/f.log"
have "$VWORK/f/comment_body.md" 'https://crates.io/crates/netcap' && ok "flagged crate header links to crates.io" || bad "no crates.io link in flagged header"
# reviewed (clean) crate -> collapsed clean-list, also linked
printf '[[review]]\ncrate = "netcap"\nversion = "0.2.0"\nreviewed_by = "carol"\n' > "$VWORK/reviews.toml"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$VWORK/c" REVIEWS="$VWORK/reviews.toml" RSA_DRY_RUN=1 PR_NUMBER="" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 GITHUB_OUTPUT="$VWORK/c_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$VWORK/c.log"
have "$VWORK/c/comment_body.md" 'no flagged findings'            && ok "clean crate folded into collapsed list" || bad "clean crate not collapsed"
have "$VWORK/c/comment_body.md" 'https://crates.io/crates/netcap' && ok "clean-list crate links to crates.io"   || bad "no crates.io link in clean list"
echo

# ===========================================================================
echo "### TEST W — Cargo.lock in a subdirectory via MANIFEST_DIR (issue #4)"
WREPO="$WORK/w/repo"; mkdir -p "$WREPO"
( cd "$WREPO"
  git init -q; git config user.email t@t.io; git config user.name tester
  mkdir -p backend
  cat > backend/Cargo.lock <<'LOCK'
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "demo"
version = "0.1.0"

[[package]]
name = "netcap"
version = "0.1.0"
LOCK
  git add -A; git commit -qm v1
  git rev-parse HEAD > "$WORK/w/base.txt"
  python3 - <<'PY'
s=open("backend/Cargo.lock").read().replace('name = "netcap"\nversion = "0.1.0"','name = "netcap"\nversion = "0.2.0"')
open("backend/Cargo.lock","w").write(s)
PY
  git add -A; git commit -qm v2
)
WBASE="$(cat "$WORK/w/base.txt")"
( cd "$WREPO"
  GITHUB_OUTPUT="$WORK/w/out.txt" MANIFEST_DIR=backend "$SCRIPTS/parse_lockdiff.sh" "$WBASE" HEAD "$WORK/w/lockdiff.tsv" >/dev/null 2>"$WORK/w/log"
)
echo "  lockdiff.tsv:"; sed 's/^/    /' "$WORK/w/lockdiff.tsv" 2>/dev/null
grep -qF "$(printf 'netcap\t0.1.0\t0.2.0')" "$WORK/w/lockdiff.tsv" && ok "subdir backend/Cargo.lock (MANIFEST_DIR=backend) diffed: netcap bump" || bad "subdir lockfile not diffed"
have "$WORK/w/out.txt" 'changed=true' && ok "changed=true for subdir lockfile" || bad "changed output wrong for subdir"
# default (root) path unchanged: no root Cargo.lock here -> changed=false, not an error
( cd "$WREPO"
  GITHUB_OUTPUT="$WORK/w/out2.txt" "$SCRIPTS/parse_lockdiff.sh" "$WBASE" HEAD "$WORK/w/lockdiff2.tsv" >/dev/null 2>>"$WORK/w/log"
)
have "$WORK/w/out2.txt" 'changed=false' && ok "default root path unchanged (no root Cargo.lock -> changed=false)" || bad "default path regressed"
echo

# ===========================================================================
echo "### TEST X — cargo-vet audits.toml imported as ledger sign-offs (issue #5)"
export RSA_FIXTURES="$FIX"
XWORK="$WORK/x"; mkdir -p "$XWORK"
python3 "$SCRIPTS/read_vet.py" "$FIX/vet/audits.toml" > "$XWORK/norm.txt" 2>"$XWORK/x.log"
echo "  --- normalized cargo-vet ---"; sed 's/^/    /' "$XWORK/norm.txt"
have "$XWORK/norm.txt" 'REVIEW.*netcap.*0.2.0.*ALL'    && ok "vet version audit -> sign-off (netcap 0.2.0)"        || bad "version audit not imported"
have "$XWORK/norm.txt" 'REVIEW.*somecrate.*1.0.1.*ALL' && ok "vet delta audit -> sign-off of the target (1.0.1)"   || bad "delta audit target not imported"
# integration: a cargo-vet sign-off suppresses capability findings (no reviews.toml)
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$XWORK/run" REVIEWS="/nonexistent" VET_AUDITS="$FIX/vet/audits.toml" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$XWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$XWORK/run.log"
have "$XWORK/out.txt" 'tier=none' && ok "cargo-vet sign-off suppresses capability findings (tier none)" \
  || bad "expected tier=none ($(grep '^tier=' "$XWORK/out.txt" 2>/dev/null))"
echo

# ===========================================================================
# ===========================================================================
echo "### TEST Y — a crate with no v0 symbols still gets diffed (issue #14)"
# facade 0.1.0 is consts/type-alias/macro only, so its rlib carries no v0
# symbols at all -- the shape of thiserror and friends. extract_symbols' grep
# used to exit 1 on that and take diff_symbols.sh's `set -e` with it, leaving
# added_syms.txt unwritten and the bump reported as clean.
export RSA_FIXTURES="$FIX"
YWORK="$WORK/y"; mkdir -p "$YWORK"
Y_OLD="$("$SCRIPTS/build_crate.sh" 0.1.0 facade "$YWORK/old" 2>"$YWORK/old.log")"
Y_NEW="$("$SCRIPTS/build_crate.sh" 0.2.0 facade "$YWORK/new" 2>"$YWORK/new.log")"
Y_OLDSYMS="$("${NM:-nm}" "$Y_OLD" 2>/dev/null | awk '{print $NF}' | grep -c '^_R')"
[ "$Y_OLDSYMS" = "0" ] && ok "facade 0.1.0 really carries zero v0 symbols" \
                       || bad "fixture drifted: old side has $Y_OLDSYMS v0 symbols, test proves nothing"
"$SCRIPTS/diff_symbols.sh" "$Y_OLD" "$Y_NEW" "$YWORK" >/dev/null 2>"$YWORK/diff.log"
[ -f "$YWORK/added_syms.txt" ] && ok "symbol diff still ran against the empty old side" \
                              || bad "symbol lane died on the empty old side (see $YWORK/diff.log)"
have "$YWORK/added_syms.txt" 'TcpStream' && ok "the capability the empty old side hid is flagged" \
                                         || bad "TcpStream missing from added symbols"
printf 'facade\t0.1.0\t0.2.0\n' > "$YWORK/lockdiff.tsv"
LOCKDIFF_TSV="$YWORK/lockdiff.tsv" WORK="$YWORK/run" REVIEWS="/nonexistent" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$YWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$YWORK/run.log"
have "$YWORK/out.txt" 'tier=critical' && ok "no-symbol -> capability bump tiers CRITICAL end to end" \
  || bad "expected tier=critical ($(grep '^tier=' "$YWORK/out.txt" 2>/dev/null))"
echo

# ===========================================================================
echo "### TEST Z — provenance: fresh-version window (a version published minutes ago)"
# The fresh fixture's created_at is computed at test time (now minus 41 min in
# UTC) so the age assertions hold no matter when the suite runs; the static
# years-old fixture (TEST AA) only ever gets older. That keeps both age tests
# deterministic without the suite failing as it ages.
export RSA_FIXTURES="$FIX"
ZWORK="$WORK/z"; mkdir -p "$ZWORK/cratesio"
python3 - "$FIX/cratesio/netcap-fresh.json.template" "$ZWORK/cratesio/netcap.json" <<'PY'
import sys
from datetime import datetime, timedelta, timezone
ts = (datetime.now(timezone.utc) - timedelta(minutes=41)).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
open(sys.argv[2], "w").write(open(sys.argv[1]).read().replace("__CREATED_AT__", ts))
PY
RSA_CRATESIO_FIXTURE="$ZWORK/cratesio" "$SCRIPTS/provenance.sh" netcap 0.1.0 0.2.0 "$ZWORK" >/dev/null 2>"$ZWORK/z.log"
echo "  --- provenance_findings.tsv ---"; sed 's/^/    /' "$ZWORK/provenance_findings.tsv" 2>/dev/null
awk -F'\t' '$1=="high"&&$2=="fresh-version"{f=1} END{exit !f}' "$ZWORK/provenance_findings.tsv" \
  && ok "version published 41 min ago -> high fresh-version" || bad "no high fresh-version finding"
have "$ZWORK/provenance_findings.tsv" 'published 41 minutes ago' && ok "detail names the real age" || bad "age missing from detail"
have "$ZWORK/provenance_findings.tsv" '86-107 minutes' && ok "detail cites the arrayref incident removal window" || bad "incident context missing"
# full pipeline: a ledger sign-off must NOT suppress it (same property as test L)
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$ZWORK/run" REVIEWS="$KWORK/reviews.toml" \
  RSA_CRATESIO_FIXTURE="$ZWORK/cratesio" RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$ZWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$ZWORK/run.log"
have "$ZWORK/out.txt" 'tier=high' && ok "fresh-version survives the sign-off (tier high, not none)" \
  || bad "expected tier=high ($(grep '^tier=' "$ZWORK/out.txt" 2>/dev/null))"
have "$ZWORK/out.txt" 'recommendation=review' && ok "fresh version flips recommendation to review" \
  || bad "expected recommendation=review"
have "$ZWORK/run/comment_body.md" '(published 41 minutes ago)' && ok "comment shows the age inline next to the versions" \
  || bad "inline age missing from comment"
have "$ZWORK/run/comment_body.md" 'fresh-version review window' && ok "headline names the fresh publish as the reason" \
  || bad "headline missing fresh-version reason"
# min-publish-age-hours=0: note only, prior tiering restored
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$ZWORK/run0" REVIEWS="$KWORK/reviews.toml" RSA_MIN_PUBLISH_AGE_HOURS=0 \
  RSA_CRATESIO_FIXTURE="$ZWORK/cratesio" RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$ZWORK/out0.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$ZWORK/run0.log"
have "$ZWORK/out0.txt" 'tier=none' && ok "min-publish-age-hours=0 restores the old tier (none)" \
  || bad "expected tier=none with window 0 ($(grep '^tier=' "$ZWORK/out0.txt" 2>/dev/null))"
have "$ZWORK/out0.txt" 'recommendation=auto-merge' && ok "window 0 -> recommendation back to auto-merge" \
  || bad "expected recommendation=auto-merge with window 0"
have "$ZWORK/run0/comment_body.md" '(published 41 minutes ago)' && ok "age note still shown with the window disabled" \
  || bad "inline age missing with window 0"
echo

# ===========================================================================
echo "### TEST AA — provenance: a years-old version gets a none-tier age note only"
AAWORK="$WORK/aa"; mkdir -p "$AAWORK/cratesio"
cp "$FIX/cratesio/netcap-old.json" "$AAWORK/cratesio/netcap.json"
RSA_CRATESIO_FIXTURE="$AAWORK/cratesio" "$SCRIPTS/provenance.sh" netcap 0.1.0 0.2.0 "$AAWORK" >/dev/null 2>"$AAWORK/aa.log"
echo "  --- provenance_findings.tsv ---"; sed 's/^/    /' "$AAWORK/provenance_findings.tsv" 2>/dev/null
awk -F'\t' '$1=="none"&&$2=="fresh-version"{f=1} END{exit !f}' "$AAWORK/provenance_findings.tsv" \
  && ok "old version -> none-tier fresh-version note carrying the age" || bad "age note missing"
have "$AAWORK/provenance_findings.tsv" 'days ago|years ago' && ok "note carries a real age" || bad "no age in note"
[ "$(awk 'END{print NR+0}' "$AAWORK/provenance_findings.tsv")" = "1" ] \
  && ok "and nothing else (single note, no findings)" || bad "unexpected extra findings"
python3 -c "import json,sys; assert json.load(open(sys.argv[1]))['tier']=='none'" "$AAWORK/provenance.json" 2>/dev/null \
  && ok "provenance.json tier none for the old version" || bad "provenance.json tier not none"
echo

# ===========================================================================
echo "### TEST AB — provenance: version missing from crates.io = removed from registry"
# arrayref 0.3.10 shape: the malicious version was DELETED from crates.io, not
# yanked, so it is simply absent from the versions array and the old code
# skipped every check (nv=None) and emitted zero findings.
ABWORK="$WORK/ab"; mkdir -p "$ABWORK/cratesio"
cp "$FIX/cratesio/netcap-ghost.json" "$ABWORK/cratesio/netcap.json"
RSA_CRATESIO_FIXTURE="$ABWORK/cratesio" "$SCRIPTS/provenance.sh" netcap 0.1.0 0.2.0 "$ABWORK" >/dev/null 2>"$ABWORK/ab.log"
echo "  --- provenance_findings.tsv ---"; sed 's/^/    /' "$ABWORK/provenance_findings.tsv" 2>/dev/null
awk -F'\t' '$1=="high"&&$2=="version-not-on-registry"{f=1} END{exit !f}' "$ABWORK/provenance_findings.tsv" \
  && ok "missing version -> high version-not-on-registry" || bad "version-not-on-registry not emitted"
have "$ABWORK/provenance_findings.tsv" 'removed from the registry' && ok "detail explains the removal" || bad "removal detail missing"
# a newly-added crate (empty old version) gets the same check
RSA_CRATESIO_FIXTURE="$ABWORK/cratesio" "$SCRIPTS/provenance.sh" netcap "" 0.2.0 "$ABWORK/new" >/dev/null 2>>"$ABWORK/ab.log"
awk -F'\t' '$1=="high"&&$2=="version-not-on-registry"{f=1} END{exit !f}' "$ABWORK/new/provenance_findings.tsv" \
  && ok "newly-added crate gets the registry check too" || bad "newly-added crate skipped the check"
# full pipeline: sign-off does not suppress it, recommendation flips
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$ABWORK/run" REVIEWS="$KWORK/reviews.toml" \
  RSA_CRATESIO_FIXTURE="$ABWORK/cratesio" RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$ABWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$ABWORK/run.log"
have "$ABWORK/out.txt" 'tier=high' && ok "version-not-on-registry survives the sign-off" \
  || bad "expected tier=high ($(grep '^tier=' "$ABWORK/out.txt" 2>/dev/null))"
have "$ABWORK/out.txt" 'recommendation=review' && ok "removed version flips recommendation to review" \
  || bad "expected recommendation=review"
have "$ABWORK/run/comment_body.md" 'no longer lists' && ok "headline names the registry removal as the reason" \
  || bad "headline missing registry-removal reason"
echo

# ===========================================================================
echo "### TEST AC — offline/disabled provenance path byte-identical to before"
ACWORK="$WORK/ac"; mkdir -p "$ACWORK"
RSA_CHECK_PROVENANCE=0 "$SCRIPTS/provenance.sh" netcap 0.1.0 0.2.0 "$ACWORK" >/dev/null 2>"$ACWORK/ac.log"
printf 'none\tprovenance-unknown\tcrates.io metadata unavailable (offline or disabled) — provenance not checked\n' > "$ACWORK/expected.tsv"
cmp -s "$ACWORK/expected.tsv" "$ACWORK/provenance_findings.tsv" \
  && ok "offline path emits exactly the provenance-unknown note (byte-identical)" \
  || bad "offline TSV drifted: $(cat "$ACWORK/provenance_findings.tsv" 2>/dev/null)"
printf '{"tier":"none","findings":[{"tier":"none","kind":"provenance-unknown","detail":"crates.io metadata unavailable"}]}\n' > "$ACWORK/expected.json"
cmp -s "$ACWORK/expected.json" "$ACWORK/provenance.json" \
  && ok "offline provenance.json byte-identical" || bad "offline JSON drifted"
[ ! -f "$ACWORK/publish_age.txt" ] && ok "no publish age manufactured offline" || bad "publish_age.txt written offline"
echo

# ===========================================================================
echo "### TEST AD — new-dependency source lane: the 2026-08-20 arrayref shape"
# carrier's own lib source is byte-identical across versions; 0.2.0 adds ONE
# manifest line pulling in dlmacro, whose build.rs downloads and executes a
# remote payload (the proc-macro1 1.0.107 shape). The symbol and source lanes
# see nothing on carrier itself; the new-dependency lane is what catches it.
export RSA_FIXTURES="$FIX"
ADWORK="$WORK/ad"; mkdir -p "$ADWORK/cratesio"
# dlmacro published 2 days ago (young) + 0 downloads -> critical; template keeps
# the fixture deterministic as the suite ages.
python3 - "$FIX/cratesio/dlmacro.json.template" "$ADWORK/cratesio/dlmacro.json" <<'PY'
import sys
from datetime import datetime, timedelta, timezone
ts = (datetime.now(timezone.utc) - timedelta(days=2)).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
open(sys.argv[2], "w").write(open(sys.argv[1]).read().replace("__CREATED_AT__", ts))
PY
# carrier's own lib source really is identical old vs new (prove the shape).
cmp -s "$FIX/carrier-0.1.0/src/lib.rs" "$FIX/carrier-0.2.0/src/lib.rs" \
  && ok "carrier lib source is byte-identical 0.1.0 -> 0.2.0 (arrayref shape)" \
  || bad "carrier fixture drifted: lib source differs, the shape is not reproduced"
# unit: the classifier alone
RSA_CRATESIO_FIXTURE="$ADWORK/cratesio" "$SCRIPTS/inspect_new_dep.sh" dlmacro 1.0.0 "$ADWORK/dl" >/dev/null 2>"$ADWORK/dl.log"
echo "  --- newdep_findings.tsv ---"; sed 's/^/    /' "$ADWORK/dl/newdep_findings.tsv" 2>/dev/null
awk -F'\t' '$1=="critical"&&$2=="new-dep-build-script"{f=1} END{exit !f}' "$ADWORK/dl/newdep_findings.tsv" \
  && ok "young + zero-download downloader build script -> critical" || bad "expected critical new-dep-build-script"
have "$ADWORK/dl/newdep_findings.tsv" 'downloads and executes a remote payload' && ok "detail names the download-and-execute behaviour" || bad "download-execute detail missing"
have "$ADWORK/dl/newdep_findings.tsv" '0 total downloads' && ok "detail carries the crate's downloads" || bad "downloads missing from detail"
[ -s "$ADWORK/dl/build_rs_excerpt.txt" ] && ok "build-script excerpt captured for inline rendering" || bad "no build-script excerpt"
# full pipeline
printf 'carrier\t0.1.0\t0.2.0\n' > "$ADWORK/lockdiff.tsv"
LOCKDIFF_TSV="$ADWORK/lockdiff.tsv" WORK="$ADWORK/run" REVIEWS="/nonexistent" \
  RSA_CRATESIO_FIXTURE="$ADWORK/cratesio" RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 \
  RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$ADWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$ADWORK/run.log"
have "$ADWORK/out.txt" 'tier=critical' && ok "arrayref shape tiers CRITICAL end to end" \
  || bad "expected tier=critical ($(grep '^tier=' "$ADWORK/out.txt" 2>/dev/null))"
have "$ADWORK/out.txt" 'recommendation=review' && ok "recommendation flips to review" || bad "expected recommendation=review"
have "$ADWORK/run/comment_body.md" 'downloads and executes a remote payload' && ok "comment carries the critical dependency finding" || bad "critical finding missing from comment"
have "$ADWORK/run/comment_body.md" 'show build script of .dlmacro. 1.0.0' && ok "comment renders the dependency's build-script excerpt inline" || bad "no inline build-script excerpt in comment"
have "$ADWORK/run/comment_body.md" 'Sign off dependency .dlmacro. 1.0.0' && ok "comment offers the dependency sign-off snippet" || bad "no dependency sign-off snippet"
echo

# ===========================================================================
echo "### TEST AE — new-dep lane: benign build.rs, and sign-off directions"
export RSA_FIXTURES="$FIX"
AEWORK="$WORK/ae"; mkdir -p "$AEWORK/cratesio"
cp "$FIX/cratesio/pm2like.json" "$AEWORK/cratesio/"
python3 - "$FIX/cratesio/dlmacro.json.template" "$AEWORK/cratesio/dlmacro.json" <<'PY'
import sys
from datetime import datetime, timedelta, timezone
ts = (datetime.now(timezone.utc) - timedelta(days=2)).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
open(sys.argv[2], "w").write(open(sys.argv[1]).read().replace("__CREATED_AT__", ts))
PY
# NEGATIVE: pm2like ships a build.rs that shells out to rustc (like
# proc-macro2/serde/libc). Execution present, no remote fetch -> never an alarm.
RSA_CRATESIO_FIXTURE="$AEWORK/cratesio" "$SCRIPTS/inspect_new_dep.sh" pm2like 1.0.0 "$AEWORK/pm" >/dev/null 2>"$AEWORK/pm.log"
echo "  --- pm2like newdep_findings.tsv ---"; sed 's/^/    /' "$AEWORK/pm/newdep_findings.tsv" 2>/dev/null
awk -F'\t' '$1=="none"&&$2=="new-dep-build-script"{f=1} END{exit !f}' "$AEWORK/pm/newdep_findings.tsv" \
  && ok "established crate's rustc-probing build.rs -> none-tier note (no false alarm)" || bad "pm2like wrongly tiered"
have "$AEWORK/pm/newdep_findings.tsv" 'no remote-fetch-and-execute tokens' && ok "note explains why it is benign" || bad "benign note detail missing"
[ ! -s "$AEWORK/pm/build_rs_excerpt.txt" ] && ok "no excerpt captured for a benign build script" || bad "excerpt captured for benign build script"
# full pipeline negative: carrier 0.1.0 -> 0.3.0 adds pm2like -> tier none
printf 'carrier\t0.1.0\t0.3.0\n' > "$AEWORK/neg.tsv"
LOCKDIFF_TSV="$AEWORK/neg.tsv" WORK="$AEWORK/neg" REVIEWS="/nonexistent" \
  RSA_CRATESIO_FIXTURE="$AEWORK/cratesio" RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 \
  RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$AEWORK/neg_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$AEWORK/neg.log"
have "$AEWORK/neg_out.txt" 'tier=none' && ok "benign new dependency -> overall tier none end to end" \
  || bad "expected tier=none ($(grep '^tier=' "$AEWORK/neg_out.txt" 2>/dev/null))"
# SUPPRESSION: signing off the DEPENDENCY (dlmacro) clears the critical finding.
printf '[[review]]\ncrate = "dlmacro"\nversion = "1.0.0"\nreviewed_by = "carol"\n' > "$AEWORK/rev-dep.toml"
printf 'carrier\t0.1.0\t0.2.0\n' > "$AEWORK/pos.tsv"
LOCKDIFF_TSV="$AEWORK/pos.tsv" WORK="$AEWORK/sup" REVIEWS="$AEWORK/rev-dep.toml" \
  RSA_CRATESIO_FIXTURE="$AEWORK/cratesio" RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 \
  RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$AEWORK/sup_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$AEWORK/sup.log"
have "$AEWORK/sup_out.txt" 'tier=none' && ok "signing off the dependency itself suppresses the finding (the ratchet)" \
  || bad "dependency sign-off did not suppress ($(grep '^tier=' "$AEWORK/sup_out.txt" 2>/dev/null))"
# NON-SUPPRESSION: signing off the AUDITED crate (carrier) must NOT hide its
# dependency's build script — the arrayref sign-off never vouched for proc-macro1.
printf '[[review]]\ncrate = "carrier"\nversion = "0.2.0"\nreviewed_by = "carol"\n' > "$AEWORK/rev-crate.toml"
LOCKDIFF_TSV="$AEWORK/pos.tsv" WORK="$AEWORK/nosup" REVIEWS="$AEWORK/rev-crate.toml" \
  RSA_CRATESIO_FIXTURE="$AEWORK/cratesio" RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 \
  RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$AEWORK/nosup_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$AEWORK/nosup.log"
have "$AEWORK/nosup_out.txt" 'tier=critical' && ok "signing off the audited crate does NOT hide its dependency's build script" \
  || bad "audited-crate sign-off wrongly suppressed the dependency finding ($(grep '^tier=' "$AEWORK/nosup_out.txt" 2>/dev/null))"
echo

# ===========================================================================
echo "### TEST AF — new-dep lane edge cases: offline, capping, unreadable"
export RSA_FIXTURES="$FIX"
AFWORK="$WORK/af"; mkdir -p "$AFWORK"
# offline: no metadata -> downloader script degrades to medium, never silent
RSA_CHECK_PROVENANCE=0 "$SCRIPTS/inspect_new_dep.sh" dlmacro 1.0.0 "$AFWORK/off" >/dev/null 2>"$AFWORK/off.log"
awk -F'\t' '$1=="medium"&&$2=="new-dep-build-script"{f=1} END{exit !f}' "$AFWORK/off/newdep_findings.tsv" \
  && ok "offline: downloader build script degrades to medium (age unknown)" || bad "offline dep not tiered medium"
have "$AFWORK/off/newdep_findings.tsv" 'metadata is unavailable' && ok "offline detail says why age is unknown" || bad "offline reason missing"
# missing source (path/git/workspace dep): logged skip, not a silent pass
"$SCRIPTS/inspect_new_dep.sh" ghostdep 9.9.9 "$AFWORK/miss" >/dev/null 2>"$AFWORK/miss.log"
have "$AFWORK/miss/newdep_findings.tsv" 'new-dep-not-inspected' && ok "no-source dependency is a logged skip, not a silent pass" || bad "no-source dep silently passed"
have "$AFWORK/miss.log" 'no extracted source' && ok "the skip is logged with a reason" || bad "skip reason not logged"
echo

# ===========================================================================
echo "### TEST AG — typosquat: a new near-miss of a crate already in the tree"
# RustSec filed the 2026-08-20 incident as "via typosquatted proc-macro1", and
# proc-macro2 was already in the victim's tree. pm2lke is one deletion from
# pm2like and ships NO build script, so this proves the name+youth signal stands
# on its own against a squat whose payload evades the build-script grep.
export RSA_FIXTURES="$FIX"
AGWORK="$WORK/ag"; mkdir -p "$AGWORK/cratesio" "$AGWORK/est"
cp "$FIX/cratesio/pm2like.json" "$AGWORK/cratesio/"; cp "$FIX/cratesio/pm2like.json" "$AGWORK/est/"
python3 - "$FIX/cratesio/pm2lke.json.template" "$AGWORK/cratesio/pm2lke.json" <<'PY'
import sys
from datetime import datetime, timedelta, timezone
ts = (datetime.now(timezone.utc) - timedelta(days=1)).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
open(sys.argv[2], "w").write(open(sys.argv[1]).read().replace("__CREATED_AT__", ts))
PY
# unit: the distance itself, and that a separator-only variant is NOT a squat
# (crates.io normalizes - and _, so serde-json and serde_json cannot coexist)
printf 'pm2like\ncarrier\nprobe_lib\n' > "$AGWORK/names.txt"
SQ="$(python3 "$SCRIPTS/typosquat.py" pm2lke "$AGWORK/names.txt" 1)"
[ "$SQ" = "$(printf '1\tpm2like')" ] && ok "typosquat.py: pm2lke is distance 1 from pm2like" || bad "wrong distance: '$SQ'"
printf 'serde-json\n' > "$AGWORK/sep.txt"
python3 "$SCRIPTS/typosquat.py" serde_json "$AGWORK/sep.txt" 1 >/dev/null 2>&1 \
  && bad "separator-only variant treated as a squat (crates.io normalizes - and _)" \
  || ok "separator-only variant is not a squat (crates.io cannot host both)"
# full pipeline: young near-miss -> high, and it flips the recommendation
printf 'carrier\t0.4.0\t0.5.0\n' > "$AGWORK/lockdiff.tsv"
LOCKDIFF_TSV="$AGWORK/lockdiff.tsv" WORK="$AGWORK/run" REVIEWS="/nonexistent" \
  RSA_CRATESIO_FIXTURE="$AGWORK/cratesio" RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 \
  RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$AGWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$AGWORK/run.log"
have "$AGWORK/out.txt" 'tier=high' && ok "brand-new near-miss with NO build script tiers HIGH" \
  || bad "expected tier=high ($(grep '^tier=' "$AGWORK/out.txt" 2>/dev/null))"
have "$AGWORK/out.txt" 'recommendation=review' && ok "typosquat flips the recommendation to review" || bad "expected recommendation=review"
have "$AGWORK/run/comment_body.md" 'is 1 character from' && ok "comment names the crate it shadows" || bad "shadowed crate not named"
have "$AGWORK/run/comment_body.md" 'one character from one you already depend on' \
  && ok "headline names the typosquat as the reason" || bad "headline missing typosquat reason"
# the false-positive guard: the SAME near-miss, but established (sha1/sha2 shape)
python3 - "$FIX/cratesio/pm2lke.json.template" "$AGWORK/est/pm2lke.json" <<'PY'
import sys
s = open(sys.argv[1]).read().replace("__CREATED_AT__", "2015-03-01T00:00:00.000000Z")
open(sys.argv[2], "w").write(s.replace('"downloads": 3', '"downloads": 483076553'))
PY
LOCKDIFF_TSV="$AGWORK/lockdiff.tsv" WORK="$AGWORK/est_run" REVIEWS="/nonexistent" \
  RSA_CRATESIO_FIXTURE="$AGWORK/est" RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 \
  RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$AGWORK/est_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$AGWORK/est.log"
have "$AGWORK/est_out.txt" 'tier=none' \
  && ok "an ESTABLISHED near-miss is a note, not an alarm (the sha1/sha2 case)" \
  || bad "established near-miss wrongly alarmed ($(grep '^tier=' "$AGWORK/est_out.txt" 2>/dev/null))"
have "$AGWORK/est_run/crates/carrier/newdep.filtered" 'not flagged' \
  && ok "the note explains why it was not flagged" || bad "no explanation in the note"
echo

# ===========================================================================
echo "==================================================================="
echo "RESULT: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] && echo "ALL GREEN" || echo "SOME FAILURES — inspect logs under $WORK"
exit "$FAIL"
