#!/usr/bin/env bash
# run_local.sh — exercise the whole rust-symbol-audit pipeline locally, offline
# where possible, against the real Rust toolchain. Proves the acceptance checks
# without needing a live GitHub Action.
#
# Requirements: rustup/cargo, rustfilt (cargo install rustfilt), a symbol lister
# (GNU nm, or rustup's llvm-nm which this script auto-detects on Windows).
set -uo pipefail

PROJECT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS="$PROJECT/scripts"
FIX="$PROJECT/test/fixtures"
# Portable scratch dir: RUNNER_TEMP on CI, else /tmp (works in Git Bash too).
WORK="${WORK:-${RUNNER_TEMP:-/tmp}/rsa-local}"
rm -rf "$WORK"; mkdir -p "$WORK"

# --- tool detection ---------------------------------------------------------
if ! command -v nm >/dev/null 2>&1; then
  NM_BIN="$(find "$(rustc --print sysroot)" -name 'llvm-nm*' 2>/dev/null | head -1)"
  if [ -n "$NM_BIN" ]; then export NM="$NM_BIN"; fi
fi
echo "NM       = ${NM:-nm}"
echo "RUSTFILT = $(command -v rustfilt || echo MISSING)"
echo "WORK     = $WORK"
echo

PASS=0; FAIL=0
ok()   { echo "  ✅ $1"; PASS=$((PASS+1)); }
bad()  { echo "  ❌ $1"; FAIL=$((FAIL+1)); }
have() { grep -qiE "$2" "$1"; }

# ===========================================================================
echo "### TEST A — build_crate + diff_symbols + risk_check (fixtures, offline)"
# Old (no net) and new (TcpStream + Command) versions of the same crate.
export RSA_FIXTURES="$FIX"
OLD_RLIB="$("$SCRIPTS/build_crate.sh" 0.1.0 netcap "$WORK/a/old" 2>"$WORK/a_old.log")"
NEW_RLIB="$("$SCRIPTS/build_crate.sh" 0.2.0 netcap "$WORK/a/new" 2>"$WORK/a_new.log")"
echo "  old rlib: ${OLD_RLIB:-<none>}"
echo "  new rlib: ${NEW_RLIB:-<none>}"
[ -f "$OLD_RLIB" ] && ok "old fixture built" || bad "old fixture build (see $WORK/a_old.log)"
[ -f "$NEW_RLIB" ] && ok "new fixture built" || bad "new fixture build (see $WORK/a_new.log)"

"$SCRIPTS/diff_symbols.sh" "$OLD_RLIB" "$NEW_RLIB" "$WORK/a" >/dev/null 2>>"$WORK/a_diff.log"
ADDED="$WORK/a/added_syms.txt"
have "$ADDED" 'TcpStream' && ok "added symbols include TcpStream" || bad "TcpStream not in added symbols"
have "$ADDED" 'Command'   && ok "added symbols include Command"   || bad "Command not in added symbols"

RISK_JSON="$("$SCRIPTS/risk_check.sh" "$ADDED" "$WORK/a" 2>>"$WORK/a_risk.log"; )"
TIER="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["tier"])' "$WORK/a/risk.json")"
echo "  overall tier = $TIER"
[ "$TIER" = "critical" ] && ok "TcpStream-gaining bump tiered CRITICAL (acceptance #3)" \
                         || bad "expected critical, got '$TIER'"
echo "  --- risk.tsv (top) ---"; head -6 "$WORK/a/risk.tsv" | sed 's/^/    /'
echo

# ===========================================================================
echo "### TEST B — parse_lockdiff on a real git repo (bump + no-change)"
REPO="$WORK/repo"; mkdir -p "$REPO/.git"
( cd "$REPO"
  git init -q
  git config user.email t@t.io; git config user.name tester
  cat > Cargo.lock <<'LOCK'
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "demo"
version = "0.1.0"
dependencies = ["netcap"]

[[package]]
name = "netcap"
version = "0.1.0"
LOCK
  git add -A; git commit -qm v1
  BASE="$(git rev-parse HEAD)"
  sed -i 's/version = "0.1.0"$/version = "0.2.0"/2' Cargo.lock  # bump netcap block (2nd occurrence)
  # ensure netcap bumped specifically:
  python3 - <<'PY'
import re,io
s=open("Cargo.lock").read()
s=s.replace('name = "netcap"\nversion = "0.1.0"','name = "netcap"\nversion = "0.2.0"')
open("Cargo.lock","w").write(s)
PY
  git add -A; git commit -qm v2
  echo "$BASE" > "$WORK/base_sha.txt"
)
BASE_SHA="$(cat "$WORK/base_sha.txt")"
( cd "$REPO"
  GITHUB_OUTPUT="$WORK/b_out.txt" "$SCRIPTS/parse_lockdiff.sh" "$BASE_SHA" HEAD "$WORK/b_lockdiff.tsv" >"$WORK/b_stdout.txt" 2>"$WORK/b.log"
)
echo "  lockdiff.tsv:"; sed 's/^/    /' "$WORK/b_lockdiff.tsv"
# grep -P (PCRE \t) is unavailable on this Git Bash locale; match a literal tab
# with grep -F instead.
grep -qF "$(printf 'netcap\t0.1.0\t0.2.0')" "$WORK/b_lockdiff.tsv" && ok "bump row emitted: netcap 0.1.0 -> 0.2.0" \
  || bad "expected netcap bump row"
have "$WORK/b_out.txt" 'changed=true' && ok "output changed=true" || bad "changed output wrong"

# no-change case: diff a commit against itself
( cd "$REPO"
  GITHUB_OUTPUT="$WORK/b_out2.txt" "$SCRIPTS/parse_lockdiff.sh" HEAD HEAD "$WORK/b_lockdiff2.tsv" >/dev/null 2>>"$WORK/b.log"
)
have "$WORK/b_out2.txt" 'changed=false' && ok "no-change -> changed=false (acceptance #4)" \
  || bad "no-change did not report changed=false"
[ ! -s "$WORK/b_lockdiff2.tsv" ] && ok "no-change TSV empty" || bad "no-change TSV should be empty"
echo

# ===========================================================================
echo "### TEST C — FULL pipeline: parse -> run_audit -> comment (dry-run, fixtures)"
export RSA_DRY_RUN=1 RSA_FIXTURES="$FIX"
CWORK="$WORK/c"; mkdir -p "$CWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$CWORK" MAX_CRATES=5 PR_NUMBER="" \
  bash -c "cd '$REPO' && GITHUB_OUTPUT='$CWORK/parse_out.txt' '$SCRIPTS/parse_lockdiff.sh' '$BASE_SHA' HEAD '$CWORK/lockdiff.tsv'" >/dev/null 2>"$CWORK/parse.log"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$CWORK" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  "$SCRIPTS/run_audit.sh" >"$CWORK/audit_stdout.txt" 2>"$CWORK/audit.log"
BODY="$CWORK/comment_body.md"
if [ -f "$BODY" ]; then
  ok "comment body produced"
  have "$BODY" 'CRITICAL'   && ok "comment flags CRITICAL"        || bad "comment missing CRITICAL"
  have "$BODY" 'TcpStream'  && ok "comment lists TcpStream symbol" || bad "comment missing TcpStream"
  have "$BODY" 'netcap'     && ok "comment names the crate"       || bad "comment missing crate name"
  have "$BODY" '\| risk \|' && ok "comment contains a symbol table (acceptance #2)" || bad "no table in comment"
else
  bad "no comment body (see $CWORK/audit.log)"
fi
echo "  --- comment_body.md ---"; sed 's/^/    /' "$BODY" 2>/dev/null | head -40
echo

# ===========================================================================
echo "### TEST D — real crates.io bump through build_crate (timing, acceptance #5)"
unset RSA_FIXTURES   # force real crates.io path
RC="once_cell"; RV_OLD="1.19.0"; RV_NEW="1.20.2"
DWORK="$WORK/d"; mkdir -p "$DWORK"
T0=$(date +%s)
D_OLD="$("$SCRIPTS/build_crate.sh" "$RV_OLD" "$RC" "$DWORK/old" 2>"$DWORK/old.log")"
D_NEW="$("$SCRIPTS/build_crate.sh" "$RV_NEW" "$RC" "$DWORK/new" 2>"$DWORK/new.log")"
T1=$(date +%s)
ELAPSED=$((T1-T0))
echo "  $RC $RV_OLD -> $RV_NEW built in ${ELAPSED}s"
echo "  old rlib: ${D_OLD:-<none>}"; echo "  new rlib: ${D_NEW:-<none>}"
[ -f "$D_OLD" ] && [ -f "$D_NEW" ] && ok "real crates.io versions built (build_crate crates.io path works)" \
  || bad "crates.io build failed (see $DWORK/*.log)"
if [ -f "$D_NEW" ]; then
  "$SCRIPTS/diff_symbols.sh" "$D_OLD" "$D_NEW" "$DWORK" >/dev/null 2>>"$DWORK/diff.log"
  N_ADDED="$(awk 'END{print NR+0}' "$DWORK/added_syms.txt" 2>/dev/null || echo 0)"
  echo "  added symbols in $RC bump: $N_ADDED"
  "$SCRIPTS/risk_check.sh" "$DWORK/added_syms.txt" "$DWORK" >/dev/null 2>>"$DWORK/risk.log"
  ok "diff+risk ran on real crate (added=$N_ADDED)"
fi
[ "$ELAPSED" -lt 240 ] && ok "single-crate bump under 4 min (${ELAPSED}s)" || bad "took ${ELAPSED}s (>240s)"
echo

# ===========================================================================
echo "### TEST E — source lane: build.rs newly added (netcap 0.2.0 -> 0.3.0)"
export RSA_FIXTURES="$FIX"          # re-export (TEST D unset it)
EWORK="$WORK/e"; mkdir -p "$EWORK"
"$SCRIPTS/inspect_source.sh" netcap 0.2.0 0.3.0 "$EWORK" >/dev/null 2>"$EWORK/e.log"
echo "  --- source_findings.tsv ---"; sed 's/^/    /' "$EWORK/source_findings.tsv" 2>/dev/null
have "$EWORK/source_findings.tsv" 'build-script' && ok "build.rs addition detected (symbol lane is blind to this)" \
  || bad "build.rs not detected"
ETIER="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["tier"])' "$EWORK/source.json" 2>/dev/null || echo none)"
[ "$ETIER" = "critical" ] && ok "malicious build.rs (shells out) tiered CRITICAL" || bad "expected critical, got '$ETIER'"
echo

# ===========================================================================
echo "### TEST F — source lane: crate becomes a proc-macro (procm 0.1.0 -> 0.2.0)"
FWORK="$WORK/f"; mkdir -p "$FWORK"
"$SCRIPTS/inspect_source.sh" procm 0.1.0 0.2.0 "$FWORK" >/dev/null 2>"$FWORK/f.log"
echo "  --- source_findings.tsv ---"; sed 's/^/    /' "$FWORK/source_findings.tsv" 2>/dev/null
have "$FWORK/source_findings.tsv" 'proc-macro' && ok "proc-macro transition detected" || bad "proc-macro not detected"
FTIER="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["tier"])' "$FWORK/source.json" 2>/dev/null || echo none)"
[ "$FTIER" = "high" ] && ok "proc-macro transition tiered HIGH" || bad "expected high, got '$FTIER'"
echo

# ===========================================================================
echo "### TEST G — config: ignore_crates + [allow] suppression"
GWORK="$WORK/g"; mkdir -p "$GWORK"
cat > "$GWORK/cfg.toml" <<'TOML'
ignore_crates = ["libc", "netcap"]

[allow]
netcap = ["TcpStream", "Command"]
TOML
python3 "$SCRIPTS/read_config.py" "$GWORK/cfg.toml" > "$GWORK/norm.txt" 2>"$GWORK/g.log"
echo "  --- normalized config ---"; sed 's/^/    /' "$GWORK/norm.txt"
have "$GWORK/norm.txt" 'IGNORE.*netcap'          && ok "read_config emits IGNORE netcap" || bad "IGNORE missing"
have "$GWORK/norm.txt" 'ALLOW.*netcap.*TcpStream' && ok "read_config emits ALLOW netcap TcpStream" || bad "ALLOW missing"

# full pipeline with netcap ignored -> overall tier none
printf 'ignore_crates = ["netcap"]\n' > "$GWORK/ignore.toml"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$GWORK/run" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  RSA_CONFIG="$GWORK/ignore.toml" GITHUB_OUTPUT="$GWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$GWORK/audit.log"
have "$GWORK/out.txt" 'tier=none'                  && ok "ignored crate -> overall tier none" || bad "expected tier=none ($(grep '^tier=' "$GWORK/out.txt" 2>/dev/null))"
have "$GWORK/run/comment_body.md" 'ignored'        && ok "comment notes the crate was ignored" || bad "comment missing 'ignored'"

# full pipeline with the critical symbols allow-listed -> tier drops from critical
cat > "$GWORK/allow.toml" <<'TOML'
[allow]
netcap = ["TcpStream", "Command", "process", "socket"]
TOML
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$GWORK/run2" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  RSA_CONFIG="$GWORK/allow.toml" GITHUB_OUTPUT="$GWORK/out2.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$GWORK/audit2.log"
echo "  out2: $(tr '\n' ' ' < "$GWORK/out2.txt")"
have "$GWORK/out2.txt" 'tier=none' && ok "allow patterns suppressed the critical symbols" \
  || bad "allow did not lower tier ($(grep '^tier=' "$GWORK/out2.txt" 2>/dev/null))"
echo

# ===========================================================================
echo "### TEST H — dependency-tree diff detects a newly-pulled crate"
HWORK="$WORK/h"; mkdir -p "$HWORK"
cat > "$HWORK/old.lock" <<'LOCK'
[[package]]
name = "probe_lib"
version = "0.1.0"

[[package]]
name = "widget"
version = "1.0.0"
LOCK
cat > "$HWORK/new.lock" <<'LOCK'
[[package]]
name = "probe_lib"
version = "0.1.0"

[[package]]
name = "widget"
version = "1.1.0"

[[package]]
name = "reqwest"
version = "0.12.0"
LOCK
NEWPKGS="$( . "$SCRIPTS/lib.sh"; comm -13 \
  <(pkg_set "$HWORK/old.lock" | awk '{print $1}' | sort -u) \
  <(pkg_set "$HWORK/new.lock" | awk '{print $1}' | sort -u) )"
echo "  new packages in tree: $(echo $NEWPKGS)"
printf '%s\n' "$NEWPKGS" | grep -qx reqwest && ok "newly-pulled dependency 'reqwest' detected" || bad "reqwest not detected"
echo

# ===========================================================================
echo "### TEST I — fail-on gating"
IWORK="$WORK/i"; mkdir -p "$IWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$IWORK/c" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  FAIL_ON=critical GITHUB_OUTPUT="$IWORK/outc.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$IWORK/c.log"
IRC=$?
echo "  run_audit exit with FAIL_ON=critical on a critical bump: $IRC"
[ "$IRC" -ne 0 ] && ok "fail-on=critical fails the check on a critical bump" || bad "expected non-zero exit, got $IRC"
[ -f "$IWORK/c/comment_body.md" ] && ok "comment still produced before failing" || bad "no comment body on gated run"

LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$IWORK/n" MAX_CRATES=5 PR_NUMBER="" RSA_DRY_RUN=1 RSA_FIXTURES="$FIX" \
  FAIL_ON=none GITHUB_OUTPUT="$IWORK/outn.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$IWORK/n.log"
INRC=$?
[ "$INRC" -eq 0 ] && ok "fail-on=none stays advisory (exit 0)" || bad "fail-on=none should exit 0, got $INRC"
echo

# ===========================================================================
echo "### TEST J — sticky comment marker present"
have "$CWORK/comment_body.md" 'rust-symbol-audit -->' && ok "comment body carries the sticky-comment marker" \
  || bad "sticky marker missing from comment body"
echo

# ===========================================================================
echo "### TEST K — review ledger ratchet: a signed-off version -> tier none"
export RSA_FIXTURES="$FIX"
KWORK="$WORK/k"; mkdir -p "$KWORK"
printf '[[review]]\ncrate = "netcap"\nversion = "0.2.0"\nreviewed_by = "carol"\n' > "$KWORK/reviews.toml"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$KWORK/run" REVIEWS="$KWORK/reviews.toml" RSA_DRY_RUN=1 PR_NUMBER="" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 GITHUB_OUTPUT="$KWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$KWORK/run.log"
have "$KWORK/out.txt" 'tier=none' && ok "signed-off netcap 0.2.0 -> overall tier none (the ratchet)" \
  || bad "expected tier=none ($(grep '^tier=' "$KWORK/out.txt" 2>/dev/null))"
have "$KWORK/run/comment_body.md" 'reviewed ✅|Signed off in the review ledger' && ok "comment shows the reviewed badge" || bad "no reviewed badge"
echo

# ===========================================================================
echo "### TEST L — advisories/provenance are NOT hidden by a stale sign-off"
LWORK="$WORK/l"; mkdir -p "$LWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$LWORK/run" REVIEWS="$KWORK/reviews.toml" \
  RSA_CRATESIO_FIXTURE="$FIX/cratesio" RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$LWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$LWORK/run.log"
have "$LWORK/out.txt" 'tier=high' && ok "provenance change survives the sign-off (tier high, not none)" \
  || bad "expected tier=high ($(grep '^tier=' "$LWORK/out.txt" 2>/dev/null))"
have "$LWORK/run/comment_body.md" 'DIFFERENT account' && ok "publisher-change surfaced despite the sign-off" || bad "publisher-change was hidden"
echo

# ===========================================================================
echo "### TEST M — provenance.sh detects a publisher change (mock crates.io)"
MWORK="$WORK/m"; mkdir -p "$MWORK"
RSA_CRATESIO_FIXTURE="$FIX/cratesio" "$SCRIPTS/provenance.sh" netcap 0.1.0 0.2.0 "$MWORK" >/dev/null 2>"$MWORK/m.log"
echo "  --- provenance_findings.tsv ---"; sed 's/^/    /' "$MWORK/provenance_findings.tsv" 2>/dev/null
have "$MWORK/provenance_findings.tsv" 'publisher-change' && ok "publisher-change detected (original-author -> attacker-acct)" || bad "publisher-change not detected"
echo

# ===========================================================================
echo "### TEST N — advisories.sh detects a RustSec/OSV advisory (mock)"
N2WORK="$WORK/n2"; mkdir -p "$N2WORK"
RSA_ADVISORY_FIXTURE="$FIX/osv" "$SCRIPTS/advisories.sh" vulncrate 1.0.0 "$N2WORK" >/dev/null 2>"$N2WORK/n.log"
echo "  --- advisory_findings.tsv ---"; sed 's/^/    /' "$N2WORK/advisory_findings.tsv" 2>/dev/null
have "$N2WORK/advisory_findings.tsv" 'RUSTSEC-2099-0001' && ok "advisory RUSTSEC-2099-0001 detected via OSV mock" || bad "advisory not detected"
echo

# ===========================================================================
echo "### TEST O — Dependabot auto-merge recommendation"
OWORK="$WORK/o"; mkdir -p "$OWORK"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$OWORK/r" REVIEWS="/nonexistent" PR_AUTHOR="dependabot[bot]" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$OWORK/r_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$OWORK/r.log"
have "$OWORK/r_out.txt" 'recommendation=review' && ok "risky bot bump -> recommendation=review" || bad "expected recommendation=review"
have "$OWORK/r/comment_body.md" 'Bot dependency bump' && ok "bot banner present in comment" || bad "bot banner missing"
LOCKDIFF_TSV="$CWORK/lockdiff.tsv" WORK="$OWORK/a" REVIEWS="$KWORK/reviews.toml" PR_AUTHOR="dependabot[bot]" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$OWORK/a_out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$OWORK/a.log"
have "$OWORK/a_out.txt" 'recommendation=auto-merge' && ok "clean (signed-off) bot bump -> recommendation=auto-merge" || bad "expected recommendation=auto-merge"
echo

# ===========================================================================
echo "### TEST P — machine-readable evidence report (audit-report.json)"
have "$OWORK/r/audit-report.json" 'rust-symbol-audit' && ok "evidence report produced" || bad "no evidence report"
python3 -c "import json; d=json.load(open('$OWORK/r/audit-report.json')); assert d['schema']==1 and d['overall_tier']=='critical' and d['crates'] and d['crates'][0]['symbols']" 2>/dev/null \
  && ok "evidence JSON well-formed (critical verdict + per-crate symbols)" || bad "evidence JSON malformed/unexpected"
echo

# ===========================================================================
echo "### TEST Q — build.rs concrete diff shown in the comment (netcap 0.2.0 -> 0.3.0)"
QWORK="$WORK/q"; mkdir -p "$QWORK"
printf 'netcap\t0.2.0\t0.3.0\n' > "$QWORK/lockdiff.tsv"
LOCKDIFF_TSV="$QWORK/lockdiff.tsv" WORK="$QWORK/run" REVIEWS="/nonexistent" \
  RSA_CHECK_PROVENANCE=0 RSA_CHECK_ADVISORIES=0 RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$QWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$QWORK/run.log"
have "$QWORK/run/comment_body.md" 'show build script' && ok "comment includes the build.rs <details> block" || bad "no build.rs details block"
have "$QWORK/run/comment_body.md" 'build-time code executed' && ok "comment shows the ACTUAL build.rs code, not just 'it changed'" || bad "build.rs content not shown"
echo

# ===========================================================================
echo "### TEST R — read_reviews.py: ALL vs ACCEPT normalization"
R2WORK="$WORK/r2"; mkdir -p "$R2WORK"
cat > "$R2WORK/reviews.toml" <<'TOML'
[[review]]
crate = "foo"
version = "1.0.0"
reviewed_by = "dave"

[[review]]
crate = "bar"
version = "2.0.0"
accept = ["TcpStream", "hyper"]
TOML
python3 "$SCRIPTS/read_reviews.py" "$R2WORK/reviews.toml" > "$R2WORK/norm.txt"
echo "  --- normalized ledger ---"; sed 's/^/    /' "$R2WORK/norm.txt"
have "$R2WORK/norm.txt" 'REVIEW.*foo.*1.0.0.*ALL.*dave'    && ok "whole-version sign-off -> ALL" || bad "ALL entry missing"
have "$R2WORK/norm.txt" 'REVIEW.*bar.*2.0.0.*ACCEPT.*hyper' && ok "per-capability accept -> ACCEPT" || bad "ACCEPT entry missing"
echo

# ===========================================================================
echo "### TEST S — newly-added crate (empty old version) parses correctly + advisory fires"
# Regression for the IFS=tab field-collapse bug: a lockdiff row 'name<TAB><TAB>ver'
# must audit as old=<none> new=ver (not old=ver new=<empty>), so the build and
# advisory lanes actually run for newly-added crates.
export RSA_FIXTURES="$FIX"
SSWORK="$WORK/s"; mkdir -p "$SSWORK"
printf 'netcap\t\t0.2.0\n' > "$SSWORK/lockdiff.tsv"
LOCKDIFF_TSV="$SSWORK/lockdiff.tsv" WORK="$SSWORK/run" REVIEWS="/nonexistent" \
  RSA_CHECK_PROVENANCE=0 RSA_ADVISORY_FIXTURE="$FIX/osv" RSA_DRY_RUN=1 PR_NUMBER="" GITHUB_OUTPUT="$SSWORK/out.txt" \
  "$SCRIPTS/run_audit.sh" >/dev/null 2>"$SSWORK/run.log"
have "$SSWORK/run.log" 'auditing netcap : <new> -> 0.2.0' \
  && ok "newly-added crate audited as old=<none> new=0.2.0 (empty-field bug fixed)" \
  || bad "newly-added crate misparsed: $(grep -o 'auditing netcap : .*' "$SSWORK/run.log" | head -1)"
have "$SSWORK/run/comment_body.md" 'RUSTSEC-2099-9999' \
  && ok "advisory lane fired for the newly-added crate (new version reached it)" \
  || bad "advisory not shown for newly-added crate"
echo

# ===========================================================================
echo "### TEST T — capability patterns: clipboard / input-device / screen-capture (issue #1)"
TTWORK="$WORK/t"; mkdir -p "$TTWORK"
cat > "$TTWORK/syms.txt" <<'SYMS'
arboard::Clipboard::set_text
<enigo::Enigo>::key_click
scrap::Capturer::frame
<nokhwa::Camera>::frame
cpal::traits::DeviceTrait::default_input_config
SYMS
"$SCRIPTS/risk_check.sh" "$TTWORK/syms.txt" "$TTWORK" >/dev/null 2>"$TTWORK/t.log"
echo "  --- risk.tsv ---"; sed 's/^/    /' "$TTWORK/risk.tsv" 2>/dev/null
TTIER="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["tier"])' "$TTWORK/risk.json" 2>/dev/null || echo none)"
[ "$TTIER" = "high" ] && ok "clipboard/input/capture symbols tier HIGH" || bad "expected high, got '$TTIER'"
have "$TTWORK/risk.tsv" 'arboard'  && ok "clipboard (arboard) flagged"    || bad "arboard not flagged"
have "$TTWORK/risk.tsv" 'enigo'    && ok "input device (enigo) flagged"   || bad "enigo not flagged"
have "$TTWORK/risk.tsv" 'Capturer' && ok "screen capture (scrap) flagged" || bad "scrap/Capturer not flagged"
echo

# ===========================================================================
echo "==================================================================="
echo "RESULT: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] && echo "ALL GREEN" || echo "SOME FAILURES — inspect logs under $WORK"
exit "$FAIL"
